# Generated by Django 3.0.7 on 2020-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='parameters',
            field=models.CharField(max_length=30),
        ),
    ]
